/* Generated by @deepseek-ai/dsh-typert-generator from the Host FaceModel — do not edit. */
import type {
  RemoteResult,
  TypertRemoteContribution,
} from '@deepseek-ai/dsh-typert-protocol'
import type { TaskBoardAttachmentResult, TaskBoardAttachmentUploadRequest, TaskBoardCreateRequest, TaskBoardDeleteResult, TaskBoardEditPatch, TaskBoardFollowupRequest, TaskBoardRejectRequest, TaskBoardReorderRequest, TaskBoardRetryRequest, TaskBoardSnapshotResult, TaskBoardTaskRef, TaskBoardTaskResult } from 'dsh-task-board/types'

declare module '@deepseek-ai/dsh-typert-protocol' {
  interface TypertRemoteNamespace$7461736b426f617264 {
    approve: (ref: TaskBoardTaskRef) => Promise<RemoteResult<TaskBoardTaskResult>>
    create: (request: TaskBoardCreateRequest) => Promise<RemoteResult<TaskBoardTaskResult>>
    delete: (ref: TaskBoardTaskRef) => Promise<RemoteResult<TaskBoardDeleteResult>>
    edit: (ref: TaskBoardTaskRef, patch: TaskBoardEditPatch) => Promise<RemoteResult<TaskBoardTaskResult>>
    followup: (ref: TaskBoardTaskRef, request: TaskBoardFollowupRequest) => Promise<RemoteResult<TaskBoardTaskResult>>
    reject: (ref: TaskBoardTaskRef, request: TaskBoardRejectRequest) => Promise<RemoteResult<TaskBoardTaskResult>>
    reopen: (ref: TaskBoardTaskRef) => Promise<RemoteResult<TaskBoardTaskResult>>
    reorder: (ref: TaskBoardTaskRef, request: TaskBoardReorderRequest) => Promise<RemoteResult<TaskBoardTaskResult>>
    retry: (ref: TaskBoardTaskRef, request: TaskBoardRetryRequest) => Promise<RemoteResult<TaskBoardTaskResult>>
    snapshot: () => Promise<RemoteResult<TaskBoardSnapshotResult>>
    start: (ref: TaskBoardTaskRef) => Promise<RemoteResult<TaskBoardTaskResult>>
    stop: (ref: TaskBoardTaskRef) => Promise<RemoteResult<TaskBoardTaskResult>>
    uploadAttachment: (request: TaskBoardAttachmentUploadRequest) => Promise<RemoteResult<TaskBoardAttachmentResult>>
  }
  interface TypertRemoteMap {
    'taskBoard/approve': (ref: TaskBoardTaskRef) => Promise<RemoteResult<TaskBoardTaskResult>>
    'taskBoard/create': (request: TaskBoardCreateRequest) => Promise<RemoteResult<TaskBoardTaskResult>>
    'taskBoard/delete': (ref: TaskBoardTaskRef) => Promise<RemoteResult<TaskBoardDeleteResult>>
    'taskBoard/edit': (ref: TaskBoardTaskRef, patch: TaskBoardEditPatch) => Promise<RemoteResult<TaskBoardTaskResult>>
    'taskBoard/followup': (ref: TaskBoardTaskRef, request: TaskBoardFollowupRequest) => Promise<RemoteResult<TaskBoardTaskResult>>
    'taskBoard/reject': (ref: TaskBoardTaskRef, request: TaskBoardRejectRequest) => Promise<RemoteResult<TaskBoardTaskResult>>
    'taskBoard/reopen': (ref: TaskBoardTaskRef) => Promise<RemoteResult<TaskBoardTaskResult>>
    'taskBoard/reorder': (ref: TaskBoardTaskRef, request: TaskBoardReorderRequest) => Promise<RemoteResult<TaskBoardTaskResult>>
    'taskBoard/retry': (ref: TaskBoardTaskRef, request: TaskBoardRetryRequest) => Promise<RemoteResult<TaskBoardTaskResult>>
    'taskBoard/snapshot': () => Promise<RemoteResult<TaskBoardSnapshotResult>>
    'taskBoard/start': (ref: TaskBoardTaskRef) => Promise<RemoteResult<TaskBoardTaskResult>>
    'taskBoard/stop': (ref: TaskBoardTaskRef) => Promise<RemoteResult<TaskBoardTaskResult>>
    'taskBoard/uploadAttachment': (request: TaskBoardAttachmentUploadRequest) => Promise<RemoteResult<TaskBoardAttachmentResult>>
  }
  interface TypertRemoteNamespaceMap {
    'taskBoard': TypertRemoteNamespace$7461736b426f617264
  }
}

export declare const TYPERT_REMOTE: TypertRemoteContribution
export default TYPERT_REMOTE
//# sourceMappingURL=typert.remote-client.d.ts.map
